
version: 2

sources:
    - name: staging
      #For bigquery:
      database: de-zoomcamp-khv

      # For postgres:
      # database: production

      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_ext
        - name: yellow_ext
         # freshness:
           # error_after: {count: 6, period: hour}
